# Site settings
title: Art Synthesizer 
email: lunamu2011@gmail.com
description: Easier doing than saying
baseurl: "/jekyll_site" 
url: "http://www.lunamu.com" 
github_username: lunamu 

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
