# Site settings
title: Art Synthesizer 
email: lunamu2011@gmail.com
description: ""
baseurl: ""
url: ""
github_username: lunamu 

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
